# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85b9d6e293299fdcb36a8688649f71f2d82d2ecf8767d3a120c714ef115c7b382e4b1e7243a35059530b5ae71f7b8bb11c9eef960957d128cfb90439d57cf69c

test:
  secret_key_base: d3bbddff5c3593bed896b47e0208577a0ae250552c4bdb9a534a7593de178cfefab36cb2979c684096a34983d94ab658eae419b70bc731bd22234e3d49bd5f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
